//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HtmlParseForm.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class chenDetail
    {
        public string UID { get; set; }
        public string ListUID { get; set; }
        public string Author { get; set; }
        public System.DateTime PostDate { get; set; }
        public string Message { get; set; }
    }
}
