//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HtmlParseForm.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FormosaList
    {
        public string UID { get; set; }
        public string Type { get; set; }
        public string Title { get; set; }
        public string Author { get; set; }
        public string Url { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> PostDate { get; set; }
        public int RepliesCount { get; set; }
        public Nullable<int> Views { get; set; }
        public System.DateTime CreateTime { get; set; }
    }
}
